---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
data:
  ALLOW_SIGNUP: "true"
  PUID: "1000"
  PGID: "1000"
  TZ: America/Toronto
  MAX_WORKERS: "1"
  WEB_CONCURRENCY: "1"
  BASE_URL: http://mealie.nixos-fw.lan
